// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_OZ7dgnlqepfCFlbbQxixZRo0kzNXb4o',
    appId: '1:338643860970:web:be72b83ba4d12d12ca8693',
    messagingSenderId: '338643860970',
    projectId: 'budi-beras',
    authDomain: 'budi-beras.firebaseapp.com',
    storageBucket: 'budi-beras.appspot.com',
    measurementId: 'G-9TKBRM04EN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6TSZO4O2YZpbO7EesmbK5w3-bX6vDmiY',
    appId: '1:338643860970:android:fbe15219df9dd69dca8693',
    messagingSenderId: '338643860970',
    projectId: 'budi-beras',
    storageBucket: 'budi-beras.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDZuVwPjZt-P0Ny_hwTo4vO8EVys_TQgQ',
    appId: '1:338643860970:ios:f1976e076d0b7637ca8693',
    messagingSenderId: '338643860970',
    projectId: 'budi-beras',
    storageBucket: 'budi-beras.appspot.com',
    iosClientId: '338643860970-o8oa0a49eje0ijo5qj479snqvlie89np.apps.googleusercontent.com',
    iosBundleId: 'com.example.skripsiBudiberas9701',
  );
}
